language: python
python:
  - "3.6"

cache: pip

install:
 - pip install -r requirements.txt
 - npm install

script:
 - cd src
 - tsc
 - python manage.py makemigrations
 - python manage.py migrate
 - python manage.py test
