#
# TwigFusion PRODUCTION SETTINGS
#

"""
Django settings for twigfusion project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

ALLOWED_HOSTS = ['*']
